#! /bin/sh

#xinput set-prop 11 354 0.7          # makes trackpoint track faster (higher numbers)
xinput set-prop 10 314 300, 300     # makes touchpad scroll slower (higher = slower)
xinput set-prop 10 316 1, 1         # makes touchpad scroll vertically and horizontally
picom -b
dunst -conf ~/.config/dunst/config &
#feh --bg-fill --random ~/Pictures/Wallpapers/
pkill pipewire
/usr/bin/pipewire &

# Ensure that xrdb has finished running before moving on to start the WM.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
