#! /bin/sh

xinput set-prop 11 354 0.9          # makes trackpoint track faster (higher numbers)
xinput set-prop 10 314 300, 300     # makes touchpad scroll slower (higher = slower)
xinput set-prop 10 316 1, 1         # makes touchpad scroll vertically and horizontally
xrandr --output LVDS-1 --gamma 0.9:0.9:0.9
picom -b
# feh --bg-fill -z ~/Pictures/Wallpapers/
 feh --bg-fill ~/Pictures/Wallpapers/RhoOphiuchiRegion26Jul25.jpg
# mpd
dunst -conf ~/.config/dunst/config &

# Ensure that xrdb has finished running before moving on to start the WM.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
